import './globals.css';
import '@repo/ui/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@repo/ui/providers';
import { Sidebar } from '@repo/ui/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Turborepo',
    description: 'Generated by create turbo',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}): JSX.Element {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider>
                    <div
                        className={'bg-background text-white min-h-screen flex'}
                    >
                        <Sidebar />
                        {children}
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
